name: Deploy My Server

on:
  push:
    branches:
      - master # 只在master上push触发部署

# 分2个job，build用于构建+部署
jobs:
  build:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本
    steps: # 自动化步骤
      #下载代码仓库
      - uses: actions/checkout@v1 
      
      # 使用action库，安装node
      - name: use Node.js  # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # 安装依赖
      - name: npm install 
        run: npm install 

      # 打包项目
      - name: Build
        run: npm run build --max-old-space-size=8192
      # 部署项目
      - name: Deploy to Staging My server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          REMOTE_HOST: ${{ secrets.MY_SERVER_IP }}   # 服务器公网地址      
          REMOTE_USER: ${{ secrets.MY_SERVER_USER }} # 服务器用户名，默认root
          REMOTE_PORT: ${{  secrets.MY_SERVER_PORT }}  # 服务器端口，默认22
          SSH_PRIVATE_KEY: ${{ secrets.MYSERVER }} #后面指定为该仓库配置的私钥
          SOURCE: './docs/.vuepress/dist/'  # 源目录，编译后生成的文件目录
          TARGET: '/opt/myblog' #服务器中，代码部署的位置
          EXCLUDE: "/dist/, /node_modules/"
          ARGS: "-rltgoDzvO"